# target_version:
# haml-lint v0.26.0

linters:
  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: false

  LeadingCommentSpace:
    enabled: false

  LineLength:
    max: 160

  RuboCop:
    enabled: true
    # These cops are incredibly noisy (or not working at all) when it comes to HAML templates,
    # so we ignore them.
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Layout/AlignParameters
      - Layout/IndentationWidth
      - Layout/LineLength
      - Layout/LeadingCommentSpace
      - Layout/TrailingEmptyLines
      - Metrics/BlockLength
      - Metrics/LineLength
      - Style/BlockNesting
      - Style/ElseAlignment
      - Style/EndOfLine
      - Style/FileName
      - Style/FinalNewline
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/Next
      - Style/WhileUntilModifier

  SpaceInsideHashAttributes:
    enabled: false
