detectors:
  Attribute:
    exclude:
      - "User#login"

  TooManyStatements:
    max_statements: 8

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
  "app/policies":
    IrresponsibleModule:
      enabled: false
  "app/mailers":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/uploaders":
    IrresponsibleModule:
      enabled: false

exclude_paths:
  - "db/"
  - "spec/"
