os: linux
dist: bionic

services:
  - postgresql

addons:
  chrome: stable

language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/

before_install:
  - bundle config set without production
  - bundle config set path vendor/bundle

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - bundle exec rails test
  - bundle exec rails test:system
